### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rubyblueberry** [szkf/package-bot#4] opened 2022-08-30 14:03 UTC
Hey!
Whenever i type p!track number carrier
I keep getting 'Error! An error has occured.'
Do you have any idea what may cause it?
<img width="358" alt="Zrzut ekranu 2022-08-30 o 15 56 17" src="https://user-images.githubusercontent.com/112482916/187457721-98de990f-bb3a-4ffd-9042-abf2683040cb.png">

**Comment by szkf** [comment] 2022-08-30 15:44
Hi @rubyblueberry,

Thanks for taking the time to report this issue!

I cannot reproduce this behaviour when trying to track an existing parcel.
There was, however, a bug that prevented the "incorrect parcel number" error from displaying. This has been fixed in #5.

Please make sure that you are using a **parcel number** as some carriers (for instance DPD) also use reference numbers, which are not supported yet. 
Can you try tracking your parcel again using [PackageBot v3.3.1](https://github.com/szkf/package-bot/releases/tag/v3.3.1)?

If this still doesn't work please include the full error message and the carrier you are trying to track.

**Comment by rubyblueberry** [comment] 2022-08-30 20:09
Hey, tried using the latest version and it did not help.
That's what I'm getting in the terminal.

root@parcelbot:~/package-bot# node ./dist/PackageBot.js
PackageBot is ready!
Error: Failed to launch the browser process!
[0830/200817.180006:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/package-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/root/package-bot/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (node:events:406:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1331:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by szkf** [comment] 2022-08-31 19:15
Hey,

Puppeteer doesn't support running as root without the `--no-sandbox` flag.
Try running PackageBot as a non-root user.

**Comment by rubyblueberry** [comment] 2022-09-01 11:37
Oh, that helped. Thank you.
One last thing - the bot goes offline right after I disconnect from the ubuntu server terminal. Do you know how to fix that?
Sorry for all those dumb questions but I'm totally clueless when it comes to coding and such stuff haha

**Comment by szkf** [comment] 2022-09-01 16:07
No worries,

To detach the `node ./dist/PackageBot.js` process from the ssh session (I assume you are using ssh to connect to your server), you need to run it in a `screen`.

Step 1 - Create a new screen session:
`screen`
Press <kbd>Space</kbd> to skip through the license and copyright notice.

Step 2 - Run PackageBot:
`node ./dist/PackageBot.js`

Step 3 - Detach from the screen session:
<kbd>Ctrl</kbd>+<kbd>a</kbd>+<kbd>d</kbd>

Now you can disconnect from the server and the process is going to keep running.

To later access the screen session:
`screen -ls` - list all screen sessions
You should see your screen listed with an id
`screen -r your-screen-id` - reattach to a screen session

Please update to [PackageBot v3.3.2](https://github.com/szkf/package-bot/releases/tag/v3.3.2) as that version includes a fix to a bug that made some parts of the tracking list feature unusable.

**Closed as completed** 2022-10-13 19:19 UTC
Labels: bug
